config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'products#index'

  # get 'products/:id' => 'products#show'
  resources :products do
    resources :reviews, except: [:index, :new, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, presence: true
  validates :description, presence: true
  validates :price_in_cents, numericality: {only_integer: true}

  has_many :review

  def price_in_dollars
    price_in_dollars = price_in_cents.to_f / 100
    sprintf("$%.2f", price_in_dollars)
  end

end

app/models/review.rb
class Review < ApplicationRecord
  validates :comment, presence: true
  validates :product_id, presence: true
  
  belongs_to :product

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
    @review = Review.new
  end

  def new
    @product = Product.new
  end

  def create
      @product = Product.new
      @product.name = params[:product][:name]
      @product.description = params[:product][:description]
      @product.price_in_cents = params[:product][:price_in_cents]
      flash[:notice] = "You have successfully created a product."


   if @product.save
      # if the product gets saved, generate a get request to "/products" (the index)
      redirect_to "/products"
    else
      # otherwise render new.html.erb
      render :new
    end

    end

    def destroy
      @product = Product.find(params[:id])
      @product.destroy
      redirect_to products_path
      flash[:notice] = "You have successfully deleted the product."
    end

    def edit
      @product = Product.find(params[:id])
    end

    def update
      @product = Product.find(params[:id])

      @product.name = params[:product][:name]
      @product.description = params[:product][:description]
      @product.price_in_cents = params[:product][:price_in_cents]
      flash[:notice] = "You have successfully updated the product."

      if @product.save
        redirect_to "/products/#{@product.id}"
      else
        render :edit
      end
    end


  end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    @product = Product.find(params[:product_id])
    @review = @product.review.new
    @review.comment = params[:review][:comment]
    # @review.product_id = params[:product][:id]

    if @review.save
    redirect_to products_path
    else
    # otherwise render new.html.erb
    render :review
    end
  end

  def edit
    @review = Review.find(params[:id])
    @product = Product.find(params[:id])
  end

  def update
    @review = Review.find(params[:id])

    @review.comment = params[:review][:comment]
    flash[:notice] = "You have successfully updated the review."

    if @review.save
      redirect_to "/products"
    else
      render :edit
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rainforest</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
    <%= link_to("New product", "/products/new") %> | <%= link_to("Index", "/products") %>
 </nav>
 <% if flash[:notice] %>
   <p class="notice"><%= flash[:notice] %></p>
   <% end %>
    <%= yield %>
  </body>
</html>

app/views/products/_product_form.html.erb
<h1>New Product</h1>

<%= form_for(@product) do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </p>
  <p>
    <%= f.label :price_in_cents %><br>
    <%= f.text_field :price_in_cents %>
  </p>
  <p>
    <%= f.submit "Save" %>
  </p>
<% end %>

app/views/products/edit.html.erb
<h1>Edit Product</h1>

<p>
  <%= link_to("Back", "/products/#{@product.id}") %>
</p>

<%= render 'product_form', product: @product %>

app/views/products/index.html.erb
<h1>Products </h1>
<li><%= link_to("New product", "/products/new") %></li>

<% @products.each do |product| %>
<ul>
<li>Product: <%= product.name %></li>
<li>Description: <%= product.description %></li>
<li>Price: <%= product.price_in_dollars %></li>
<li><%= link_to("Check it", "/products/#{product.id}") %></li>
</ul>
<%end%>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= link_to 'See all products', products_path %>
<%= render 'product_form', product: @product %>


<% if @product.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

    <ul>
    <% @product.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/products/show.html.erb
<%= link_to("Back to Products", "/products") %> | <%= link_to("Edit", edit_product_path) %> | <%= link_to("Delete", "/products/#{@product.id}", method: :delete, data: {confirm: "Are you sure you want to delete this product?"})  %>


<p><%= @product.name %>, <%= @product.description %></p>
<%= @product.price_in_cents %>

<ul>
  <% @product.review.each do |review| %>
  <li>
    <%= review.comment %>  |  <%= review.created_at %> <%= link_to("Edit", edit_product_review_path(@product.id, review.id))  %>



  </li>
  <% end %>
</ul>



<h4>New Review</h4>

<%= render '/reviews/form', product: @product %>

  <!-- <%= form_for([@product, @review]) do |f| %>
    <% if @review.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

        <ul>
        <% @review.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :comment %><br />
      <%= f.text_area :comment %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %> -->

app/views/reviews/_form.html.erb
<%= form_for([@product, @review]) do |f| %>

  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :comment %><br />
    <%= f.text_area :comment %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h4>Edit Review</h4>

<%= render 'form', product: @product %>

app/views/reviews/review.html.erb
<%= link_to("Edit", "/reviews/#{@review.id}/edit") %>
<%= render 'form', review: @review %>